const skills = [
    {id: 1, skill: 'PHP', stars: 4},
    {id: 2, skill: 'Laravel', stars: 4},
    {id: 3, skill: 'Angular', stars: 4},
    {id: 4, skill: 'Vue.js', stars: 5},
    {id: 5, skill: 'JavaScript', stars: 5},
    {id: 6, skill: 'Express', stars: 5},
    {id: 7, skill: 'TypeScript', stars: 5},
    {id: 34, skill: 'Swift', stars: 4},
    {id: 10, skill: 'AWS', stars: 4},
    {id: 11, skill: 'Azure', stars: 2},
    {id: 34, skill: 'GCP (Google Cloud Platform)', stars: 4},
    {id: 12, skill: 'Flutter', stars: 5},
    {id: 13, skill: 'Dart', stars: 5},
    {id: 14, skill: 'Python', stars: 3},
    {id: 15, skill: 'HTML CSS', stars: 5},
    {id: 16, skill: 'Electron', stars: 5},
    {id: 17, skill: 'React', stars: 5},
    {id: 18, skill: 'React-Native', stars: 5},
    {id: 19, skill: 'Node.js', stars: 5},
    {id: 20, skill: 'Kotlin', stars: 4},
    {id: 21, skill: 'Git', stars: 5},
    {id: 22, skill: 'Docker', stars: 5},
    {id: 23, skill: 'PM2', stars: 4},
    {id: 24, skill: 'NGINX', stars: 4},
    {id: 25, skill: 'MongoDB', stars: 5},
    {id: 26, skill: 'MySQL', stars: 5},
    {id: 27, skill: 'PostgreSQL', stars: 5},
    {id: 28, skill: 'DynamoDB', stars: 5},
    {id: 29, skill: 'Java', stars: 4},
    {id: 30, skill: 'Next.js', stars: 5},
    {id: 31, skill: 'Nest.js', stars: 5},
    {id: 32, skill: 'Lambda', stars: 5},
    {id: 33, skill: 'Serverless', stars: 5},
    {id: 35, skill: 'Jest', stars: 5},
    {id: 36, skill: 'Cypress', stars: 4},
    {id: 37, skill: 'Jenkins', stars: 4},
    {id: 38, skill: 'CI/CD', stars: 5},
    {id: 39, skill: 'Scrum', stars: 4},
    {id: 40, skill: 'Kanban', stars: 4},
    {id: 41, skill: 'TDD', stars: 4},
    {id: 42, skill: 'DDD', stars: 4},
    {id: 43, skill: 'Microservices', stars: 5},
    {id: 44, skill: 'RESTful APIs', stars: 5},
    {id: 45, skill: 'GraphQL', stars: 4},
    {id: 46, skill: 'Agile Methodologies', stars: 4},
    {id: 47, skill: 'DevOps', stars: 4},
    {id: 48, skill: 'IA Agents', stars: 5},
    {id: 49, skill: 'ChatGPT API', stars: 5},
    {id: 50, skill: 'Gemini', stars: 3},
    {id: 51, skill: 'Vertex', stars: 3},
    {id: 52, skill: 'Bedrock', stars: 4},
    {id: 53, skill: 'LLM', stars: 4},

]

export default skills;