const skills = [
    [{ id: 1, skill: 'PHP', stars: 4 },
    { id: 2, skill: 'Laravel', stars: 4 },
    { id: 3, skill: 'Angular', stars: 5 },
    { id: 4, skill: 'Vue.js', stars: 5 },
    { id: 5, skill: 'JavaScript', stars: 5 },
    { id: 6, skill: 'Express', stars: 5 },
    { id: 7, skill: 'TypeScript', stars: 5 },
    { id: 34, skill: 'Swift', stars: 3 },
    { id: 10, skill: 'AWS', stars: 5 },
    { id: 12, skill: 'Flutter', stars: 4 },
    { id: 13, skill: 'Dart', stars: 4 },
    { id: 14, skill: 'Python', stars: 4 },
    { id: 15, skill: 'HTML CSS', stars: 5 },
    { id: 16, skill: 'Electron', stars: 5 },
    { id: 17, skill: 'React', stars: 5 },
    { id: 18, skill: 'React-Native', stars: 5 },
    { id: 19, skill: 'Node.js', stars: 5 },
    { id: 20, skill: 'Kotlin', stars: 4 },
    { id: 21, skill: 'Git', stars: 5 },
    { id: 22, skill: 'Docker', stars: 5 },
    { id: 23, skill: 'PM2', stars: 4 },
    { id: 24, skill: 'NGINX', stars: 4 },
    { id: 25, skill: 'MongoDB', stars: 5 },
    { id: 26, skill: 'MySQL', stars: 5 },
    { id: 27, skill: 'PostgreSQL', stars: 5 },
    { id: 28, skill: 'DynamoDB', stars: 5 },
    { id: 29, skill: 'Java', stars: 3 },
    { id: 30, skill: 'Next.js', stars: 5 },
    { id: 31, skill: 'Nest.js', stars: 5 },
    { id: 32, skill: 'Lambda', stars: 5 },
    { id: 33, skill: 'Serverless', stars: 5 }]
]

export default skills;